### PR TITLE
Pick error class for responses without bodies

### LINKED ISSUE #51: TypeError: Cannot read property 'error' of null
**Describe the bug**

401 error codes not handled by `BaseClient.js`

```javascript
const client =  new recurly.Client(apiKey);
await this.client.listPlans({ limit: 2 }).count();
```

TypeError: Cannot read property 'error' of null

    at IncomingMessage.<anonymous> (/Users/XYZ/node_modules/recurly/lib/recurly/BaseClient.js:71:50)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```
// BaseCleint.js

const recurlyResponse = new Response(httpResponse, rbody, recurlyRequest)

/*
recurlyResponse = Response {
      request: Request { method: 'HEAD', path: '/plans?limit=2', body: null },
      body: null, <---- Body is null with this 401 error
      status: 401,
      requestId: '528928cb49dbe604-LHR',
      rateLimit: NaN,
      rateLimitRemaining: NaN,
      rateLimitReset: Invalid Date,
      recordCount: null,
      date: 'Sun, 20 Oct 2019 07:08:14 GMT',
      proxyMetadata: { server: 'cloudflare', 'cf-ray': '528928cb49dbe604-LHR' }
    }
*/

if (recurlyResponse.status < 200 || recurlyResponse.status > 299) {
    const errBody = recurlyResponse.body.error // <--- HERE

// ...rest
```

**To Reproduce**

```javascript
const client =  new recurly.Client(apiKey);
await this.client.listPlans({ limit: 2 }).count();
```

**Expected behavior**

To display a useful 401 error

### PR DESCRIPTION
**Pull request by bhelx**
Resolves #51

The client uses the body to delegate which error class to use. But `HEAD` requests do not return with bodies. This ensures there is a fallback procedure to pick an error class. I think this has opened up a deeper question about how we organize and handle errors and we will address this in the next version.

### CODE REVIEW

File: lib/recurly/BaseClient.js [hunk 1]
```diff
@@ -106,6 +101,47 @@ class BaseClient {
...
+      // if we don't have a body, we determine the error
+      // based on the http status code
+      } else {
+        let err = new ApiError('Unknown Error', 'unknown')
+
+        if (resp.status === 400) {
+          err = new apiErrors.BadRequestError('Bad Request', 'bad_request')
+        } else if (resp.status >= 401 && resp.status <= 403) {
+          err = new apiErrors.UnauthorizedError('Request not authorized. Perhaps your API key or site-id is incorrect?', 'unauthorized')
+        } else if (resp.status === 400) {
```
Comment (drewish) [inline lib/recurly/BaseClient.js]: Copy pasta? I'd assume this should be 404

File: lib/recurly/BaseClient.js [hunk 2]
```diff
@@ -106,6 +101,47 @@ class BaseClient {
...
+          err = new apiErrors.NotFoundError('Resource Not Found', 'not_found')
+        } else if (resp.status === 422) {
+          err = new apiErrors.ValidationError('Request not valid', 'validation')
+        } else if (resp.status === 500) {
+          err = new apiErrors.InternalServerError('Internal Server Error', 'internal_server_error')
```
Comment (drewish) [inline lib/recurly/BaseClient.js]: Do we want to phrase this in a way that makes it clearer the error is on our side? Recurly Server Error?
