### PR TITLE
Fixing bugs in the Pager

### LINKED ISSUE #105: Clarification listInvoices on params; limit does not seem to be working
I've got a few questions about the [listInvoices](https://recurly.github.io/recurly-client-node/#clientlistinvoices) method.

Per the docs, if I pass `options.params.limit = 20`, I would expect the 20 records back:
```javascript
console.log('recurly v' + require('recurly/package.json').version)
const options = {
  params: {
    limit: 20
  }
}
const invoicePager = await client.listInvoices(options)
console.log('Pager count:', await invoicePager.count())
let total = 0
for await (const invoice of invoicePager.each()) {
  total += 1
  if (total > 20) {
    console.log('Over the limit of 20: ' + total)
    break
  }
}
```

Which outputs:
```
recurly v3.6.0
Pager count: null
Over the limit of 20: 21
```

If I pass `params.limit = 20`, I would expect it not work, but strangely the Pager count is null:
```javascript
console.log('recurly v' + require('recurly/package.json').version)
const params = {
  limit: 20
}
const invoicePager = await client.listInvoices(params)
console.log('Pager count:', await invoicePager.count())
let total = 0
for await (const invoice of invoicePager.each()) {
  total += 1
  if (total > 20) {
    console.log('Over the limit of 20: ' + total)
    break
  }
}
```

Which outputs:
```
recurly v3.6.0
Pager count: 1812
Over the limit of 20: 21
```

If I use `options.params.beginTime`, Pager.count() recognizes it, but it still keep returning:
```javascript
console.log('recurly v' + require('recurly/package.json').version)
// In our sandbox account, we have 8 invoices that fit this criteria
const params = {
  beginTime: '2020-04-20'
}
const invoicePager = await client.listInvoices(params)
console.log('Pager count:', await invoicePager.count())
let lastInvoice
let total = 0
for await (const invoice of invoicePager.each()) {
  total += 1
  lastInvoice = invoice
  if (total > 8) {
    console.log('Over the expected amount')
    break
  }
}
console.log(lastInvoice.createdAt)
```

Which outputs:
```
recurly v3.6.0
Pager count: 8
Over the expected amount
2020-04-18T21:14:52.000Z
```

However, if I pass `params.beginTime`, I would expect it not work, and the Pager count is null:
```javascript
console.log('recurly v' + require('recurly/package.json').version)
// In our sandbox account, we have 8 invoices that fit this criteria
const options = {
  params: {
    beginTime: '2020-04-20'
  }
}
const invoicePager = await client.listInvoices(options)
console.log('Pager count:', await invoicePager.count())
let lastInvoice
let total = 0
for await (const invoice of invoicePager.each()) {
  total += 1
  lastInvoice = invoice
  if (total > 8) {
    console.log('Over the expected amount')
    break
  }
}
console.log(lastInvoice.createdAt)
```

Which outputs:
```
recurly v3.6.0
Pager count: 8
Over the expected amount
2020-04-18T21:14:52.000Z
```

Is it something with how the API is being auto-generated?

### PR DESCRIPTION
**Pull request by douglasmiller**
Resolves #105 

There are two bugs that are fixed here.

1. The error handling code was silently failing when a non-2XX response contained a `Content-Type: application/json` header but no body.
2. The `Pager` class was not sending the original params if the `count()` method was called prior to iteration.

### CODE REVIEW

File: lib/recurly/Pager.js [hunk 1]
```diff
@@ -38,6 +38,10 @@ class Pager {
    */
   async count () {
     const empty = await this.client._makeRequest('HEAD', this.path, null, { params: this._consumeParams() })
+    // Reset this value to false so that the actual paging attempt
+    // will include params in the initial request.
+    this._paramsConsumed = false
+    console.log(empty.getResponse())
```
Comment (bhelx) [inline lib/recurly/Pager.js:44]: stray `console.log`

Comment (douglasmiller) [reply lib/recurly/Pager.js:44]: oops

File: lib/recurly/Pager.js [hunk 2]
```diff
@@ -51,7 +51,7 @@ class Pager {
   async first () {
```
Comment (bhelx) [inline lib/recurly/Pager.js:51]: If you were to iterate over this pager after calling `first`, I believe it could result in iterating 1 item at a time. What do you think about this to get rid of the statefulness:

```js
let params = Object.assign({}, this.params)
params.limit = 1
let results = await this.client._makeRequest('GET', this.path, null, { params: params })
```
